root = "."
tmp_dir = "tmp"

[build]
  include_ext = ['go']
  exclude_regex = ['_test.go']
  exclude_dir = ['tmp', 'web']
  delay = 500
  kill_delay = "0s"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"