// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) error
	GetUserByUsername(ctx context.Context, username string) (string, error)
	GetUserDataByUserId(ctx context.Context, userID string) (GetUserDataByUserIdRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
}

var _ Querier = (*Queries)(nil)
